export const seedCategories = [
  { name: 'Electronics', slug: 'electronics', description: 'Cutting-edge technology and gadgets', image_url: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 1, is_active: true },
  { name: 'Fashion', slug: 'fashion', description: 'Latest trends in clothing and accessories', image_url: 'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 2, is_active: true },
  { name: 'Home & Kitchen', slug: 'home-kitchen', description: 'Everything for your home', image_url: 'https://images.pexels.com/photos/1080696/pexels-photo-1080696.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 3, is_active: true },
  { name: 'Sports & Outdoors', slug: 'sports-outdoors', description: 'Gear for active lifestyle', image_url: 'https://images.pexels.com/photos/248547/pexels-photo-248547.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 4, is_active: true },
  { name: 'Books', slug: 'books', description: 'Expand your knowledge', image_url: 'https://images.pexels.com/photos/1907785/pexels-photo-1907785.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 5, is_active: true },
  { name: 'Beauty & Personal Care', slug: 'beauty-personal-care', description: 'Beauty essentials', image_url: 'https://images.pexels.com/photos/3785147/pexels-photo-3785147.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 6, is_active: true },
  { name: 'Toys & Games', slug: 'toys-games', description: 'Fun for all ages', image_url: 'https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 7, is_active: true },
  { name: 'Automotive', slug: 'automotive', description: 'Car accessories and parts', image_url: 'https://images.pexels.com/photos/164634/pexels-photo-164634.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 8, is_active: true },
  { name: 'Health & Wellness', slug: 'health-wellness', description: 'Take care of yourself', image_url: 'https://images.pexels.com/photos/3823495/pexels-photo-3823495.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 9, is_active: true },
  { name: 'Pet Supplies', slug: 'pet-supplies', description: 'Everything for your pets', image_url: 'https://images.pexels.com/photos/1904105/pexels-photo-1904105.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 10, is_active: true },
  { name: 'Furniture', slug: 'furniture', description: 'Modern and classic furniture pieces', image_url: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 11, is_active: true },
  { name: 'Garden & Outdoor Living', slug: 'garden-outdoor-living', description: 'Transform your outdoor space', image_url: 'https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 12, is_active: true },
  { name: 'Office & School Supplies', slug: 'office-school-supplies', description: 'Everything for work and school', image_url: 'https://images.pexels.com/photos/256490/pexels-photo-256490.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 13, is_active: true },
  { name: 'Music & Instruments', slug: 'music-instruments', description: 'Musical instruments and equipment', image_url: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 14, is_active: true },
  { name: 'Jewelry & Watches', slug: 'jewelry-watches', description: 'Elegant jewelry and timepieces', image_url: 'https://images.pexels.com/photos/2407175/pexels-photo-2407175.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 15, is_active: true },
  // Subcategories
  { name: 'Smartphones', slug: 'smartphones', description: 'Latest smartphones and mobile devices', image_url: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 16, is_active: true },
  { name: 'Laptops', slug: 'laptops', description: 'Portable computers and notebooks', image_url: 'https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 17, is_active: true },
  { name: 'Men\'s Clothing', slug: 'mens-clothing', description: 'Fashion for men', image_url: 'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 18, is_active: true },
  { name: 'Women\'s Clothing', slug: 'womens-clothing', description: 'Fashion for women', image_url: 'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 19, is_active: true },
  { name: 'Kitchen Appliances', slug: 'kitchen-appliances', description: 'Essential kitchen gadgets', image_url: 'https://images.pexels.com/photos/324028/pexels-photo-324028.jpeg?auto=compress&cs=tinysrgb&w=800', display_order: 20, is_active: true },
];

export const seedProducts = (categoryIds: Record<string, string>) => [
  {
    name: 'Wireless Noise-Canceling Headphones',
    slug: 'wireless-noise-canceling-headphones',
    description: 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and superior sound quality. Perfect for music lovers and travelers.',
    category_id: categoryIds['electronics'],
    base_price: 299.99,
    actual_MRP: 449.99,
    discounted_price: 299.99,
    percentage_discount: 33,
    images: ['https://images.pexels.com/photos/3825517/pexels-photo-3825517.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['wireless', 'audio', 'headphones', 'noise-canceling'],
    rating: 4.7,
    review_count: 342,
    stock_quantity: 150,
    is_featured: true,
    is_new_arrival: true,
    is_hot_deal: true,
    has_offer: true,
    variants: { colors: ['Black', 'Silver', 'Navy Blue'], sizes: [] },
    specifications: { battery: '30 hours', connectivity: 'Bluetooth 5.0', weight: '250g' },
  },
  {
    name: '4K Ultra HD Smart TV 55"',
    slug: '4k-ultra-hd-smart-tv-55',
    description: 'Stunning 55-inch 4K display with HDR support, built-in streaming apps, and voice control. Transform your entertainment experience.',
    category_id: categoryIds['electronics'],
    base_price: 699.99,
    actual_MRP: 999.99,
    discounted_price: 699.99,
    percentage_discount: 30,
    images: ['https://images.pexels.com/photos/1201996/pexels-photo-1201996.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['tv', 'smart-tv', '4k', 'entertainment'],
    rating: 4.6,
    review_count: 567,
    stock_quantity: 45,
    is_featured: true,
    is_hot_deal: true,
    variants: null,
    specifications: { resolution: '3840x2160', refresh_rate: '120Hz', hdmi_ports: '4' },
  },
  {
    name: 'Premium Cotton T-Shirt',
    slug: 'premium-cotton-t-shirt',
    description: 'Soft, breathable, and stylish premium cotton t-shirt. Perfect for casual wear. Available in multiple colors and sizes.',
    category_id: categoryIds['fashion'],
    base_price: 24.99,
    actual_MRP: 39.99,
    discounted_price: 24.99,
    percentage_discount: 37,
    images: ['https://images.pexels.com/photos/1192609/pexels-photo-1192609.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['clothing', 't-shirt', 'cotton', 'casual'],
    rating: 4.5,
    review_count: 892,
    stock_quantity: 500,
    is_new_arrival: true,
    has_offer: true,
    variants: { colors: ['White', 'Black', 'Navy', 'Gray'], sizes: ['S', 'M', 'L', 'XL', 'XXL'] },
    specifications: { material: '100% Cotton', care: 'Machine wash cold' },
  },
  {
    name: 'Designer Leather Handbag',
    slug: 'designer-leather-handbag',
    description: 'Elegant leather handbag with spacious interior and multiple compartments. Perfect for work or evening events.',
    category_id: categoryIds['fashion'],
    base_price: 189.99,
    actual_MRP: 299.99,
    discounted_price: 189.99,
    percentage_discount: 37,
    images: ['https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['handbag', 'leather', 'accessories', 'luxury'],
    rating: 4.8,
    review_count: 234,
    stock_quantity: 80,
    is_featured: true,
    variants: { colors: ['Brown', 'Black', 'Burgundy'], sizes: [] },
    specifications: { material: 'Genuine Leather', dimensions: '30x25x12cm' },
  },
  {
    name: 'Stainless Steel Cookware Set',
    slug: 'stainless-steel-cookware-set',
    description: '10-piece professional-grade stainless steel cookware set. Includes pots, pans, and lids for all your cooking needs.',
    category_id: categoryIds['home-kitchen'],
    base_price: 249.99,
    actual_MRP: 449.99,
    discounted_price: 249.99,
    percentage_discount: 44,
    images: ['https://images.pexels.com/photos/4686822/pexels-photo-4686822.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['cookware', 'kitchen', 'stainless-steel', 'cooking'],
    rating: 4.7,
    review_count: 445,
    stock_quantity: 120,
    is_featured: true,
    is_hot_deal: true,
    has_offer: true,
    variants: null,
    specifications: { pieces: '10', material: 'Stainless Steel', oven_safe: 'Up to 500°F' },
  },
  {
    name: 'Electric Coffee Maker',
    slug: 'electric-coffee-maker',
    description: 'Programmable coffee maker with thermal carafe. Brew perfect coffee every morning with customizable settings.',
    category_id: categoryIds['home-kitchen'],
    base_price: 79.99,
    actual_MRP: 129.99,
    discounted_price: 79.99,
    percentage_discount: 38,
    images: ['https://images.pexels.com/photos/324028/pexels-photo-324028.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['coffee', 'appliance', 'kitchen', 'beverage'],
    rating: 4.4,
    review_count: 678,
    stock_quantity: 200,
    has_offer: true,
    variants: null,
    specifications: { capacity: '12 cups', features: 'Programmable, Auto-shutoff' },
  },
  {
    name: 'Professional Yoga Mat',
    slug: 'professional-yoga-mat',
    description: 'Extra thick, non-slip yoga mat with carrying strap. Perfect for yoga, pilates, and fitness exercises.',
    category_id: categoryIds['sports-outdoors'],
    base_price: 39.99,
    actual_MRP: 59.99,
    discounted_price: 39.99,
    percentage_discount: 33,
    images: ['https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['yoga', 'fitness', 'exercise', 'mat'],
    rating: 4.6,
    review_count: 523,
    stock_quantity: 300,
    is_new_arrival: true,
    has_offer: true,
    variants: { colors: ['Purple', 'Blue', 'Pink', 'Green'], sizes: [] },
    specifications: { thickness: '6mm', material: 'TPE', dimensions: '183x61cm' },
  },
  {
    name: 'Camping Tent 4-Person',
    slug: 'camping-tent-4-person',
    description: 'Spacious 4-person camping tent with waterproof design and easy setup. Perfect for family camping trips.',
    category_id: categoryIds['sports-outdoors'],
    base_price: 159.99,
    actual_MRP: 249.99,
    discounted_price: 159.99,
    percentage_discount: 36,
    images: ['https://images.pexels.com/photos/2398220/pexels-photo-2398220.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['camping', 'tent', 'outdoor', 'adventure'],
    rating: 4.5,
    review_count: 289,
    stock_quantity: 75,
    is_hot_deal: true,
    variants: { colors: ['Green', 'Orange'], sizes: [] },
    specifications: { capacity: '4 persons', setup_time: '10 minutes', waterproof: 'Yes' },
  },
  {
    name: 'Bestselling Fiction Novel Set',
    slug: 'bestselling-fiction-novel-set',
    description: 'Collection of award-winning fiction novels. Perfect for book lovers and collectors.',
    category_id: categoryIds['books'],
    base_price: 49.99,
    actual_MRP: 79.99,
    discounted_price: 49.99,
    percentage_discount: 37,
    images: ['https://images.pexels.com/photos/46274/pexels-photo-46274.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['books', 'fiction', 'reading', 'literature'],
    rating: 4.8,
    review_count: 1245,
    stock_quantity: 400,
    is_featured: true,
    variants: null,
    specifications: { format: 'Paperback', books_included: '5', language: 'English' },
  },
  {
    name: 'Premium Face Serum Set',
    slug: 'premium-face-serum-set',
    description: 'Complete skincare set with vitamin C serum, hyaluronic acid, and retinol. Transform your skin in 30 days.',
    category_id: categoryIds['beauty-personal-care'],
    base_price: 89.99,
    actual_MRP: 149.99,
    discounted_price: 89.99,
    percentage_discount: 40,
    images: ['https://images.pexels.com/photos/3785147/pexels-photo-3785147.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['skincare', 'serum', 'beauty', 'anti-aging'],
    rating: 4.7,
    review_count: 734,
    stock_quantity: 250,
    is_new_arrival: true,
    has_offer: true,
    variants: null,
    specifications: { bottle_size: '30ml each', ingredients: 'Natural & Organic' },
  },
  {
    name: 'Building Blocks Set 1000pcs',
    slug: 'building-blocks-set-1000pcs',
    description: 'Creative building blocks set with 1000 pieces. Encourages creativity and problem-solving skills.',
    category_id: categoryIds['toys-games'],
    base_price: 44.99,
    actual_MRP: 74.99,
    discounted_price: 44.99,
    percentage_discount: 40,
    images: ['https://images.pexels.com/photos/1134643/pexels-photo-1134643.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['toys', 'blocks', 'kids', 'educational'],
    rating: 4.9,
    review_count: 2145,
    stock_quantity: 500,
    is_featured: true,
    variants: null,
    specifications: { pieces: '1000', age_range: '6+', material: 'ABS Plastic' },
  },
  {
    name: 'Car Phone Mount Dashboard',
    slug: 'car-phone-mount-dashboard',
    description: 'Universal car phone holder with 360° rotation and strong suction. Safe and convenient hands-free driving.',
    category_id: categoryIds['automotive'],
    base_price: 19.99,
    actual_MRP: 39.99,
    discounted_price: 19.99,
    percentage_discount: 50,
    images: ['https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['automotive', 'accessories', 'phone-mount', 'safety'],
    rating: 4.4,
    review_count: 567,
    stock_quantity: 600,
    has_offer: true,
    variants: null,
    specifications: { compatibility: 'Universal', rotation: '360°' },
  },
  {
    name: 'Fitness Tracker Smartwatch',
    slug: 'fitness-tracker-smartwatch',
    description: 'Advanced fitness tracker with heart rate monitor, sleep tracking, and 20+ sport modes. Stay healthy and connected.',
    category_id: categoryIds['health-wellness'],
    base_price: 129.99,
    actual_MRP: 199.99,
    discounted_price: 129.99,
    percentage_discount: 35,
    images: ['https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['fitness', 'smartwatch', 'health', 'tracker'],
    rating: 4.6,
    review_count: 892,
    stock_quantity: 180,
    is_new_arrival: true,
    is_hot_deal: true,
    variants: { colors: ['Black', 'Rose Gold', 'Silver'], sizes: [] },
    specifications: { battery: '7 days', waterproof: '5ATM', display: '1.4" AMOLED' },
  },
  {
    name: 'Premium Dog Food 30lb Bag',
    slug: 'premium-dog-food-30lb-bag',
    description: 'Natural, grain-free dog food with real meat as the first ingredient. Complete nutrition for your furry friend.',
    category_id: categoryIds['pet-supplies'],
    base_price: 59.99,
    actual_MRP: 99.99,
    discounted_price: 59.99,
    percentage_discount: 40,
    images: ['https://images.pexels.com/photos/4588051/pexels-photo-4588051.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['pet-food', 'dog', 'nutrition', 'grain-free'],
    rating: 4.8,
    review_count: 1567,
    stock_quantity: 350,
    has_offer: true,
    variants: { colors: [], sizes: ['Small Breed', 'Large Breed'] },
    specifications: { weight: '30 lbs', protein: '30%', ingredients: 'Real Chicken' },
  },
  {
    name: 'Wireless Gaming Mouse',
    slug: 'wireless-gaming-mouse',
    description: 'High-precision wireless gaming mouse with customizable RGB lighting and programmable buttons.',
    category_id: categoryIds['electronics'],
    base_price: 79.99,
    actual_MRP: 129.99,
    discounted_price: 79.99,
    percentage_discount: 38,
    images: ['https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['gaming', 'mouse', 'wireless', 'rgb'],
    rating: 4.7,
    review_count: 445,
    stock_quantity: 220,
    is_featured: true,
    is_hot_deal: true,
    has_offer: true,
    variants: null,
    specifications: { dpi: '16000', buttons: '8 programmable', battery: '70 hours' },
  },
  {
    name: 'Denim Jacket Classic Fit',
    slug: 'denim-jacket-classic-fit',
    description: 'Timeless denim jacket with classic fit. A wardrobe essential that never goes out of style.',
    category_id: categoryIds['fashion'],
    base_price: 69.99,
    actual_MRP: 119.99,
    discounted_price: 69.99,
    percentage_discount: 42,
    images: ['https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['jacket', 'denim', 'outerwear', 'casual'],
    rating: 4.6,
    review_count: 678,
    stock_quantity: 180,
    has_offer: true,
    variants: { colors: ['Light Blue', 'Dark Blue', 'Black'], sizes: ['S', 'M', 'L', 'XL'] },
    specifications: { material: '100% Cotton Denim', fit: 'Classic' },
  },
  {
    name: 'Comfortable Sofa with Cushions',
    slug: 'comfortable-sofa-with-cushions',
    description: 'Spacious and comfortable sofa with premium cushions. Perfect for your living room. Available in multiple colors.',
    category_id: categoryIds['furniture'],
    base_price: 599.99,
    actual_MRP: 899.99,
    discounted_price: 599.99,
    percentage_discount: 33,
    images: ['https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['furniture', 'sofa', 'living-room', 'comfort'],
    rating: 4.7,
    review_count: 356,
    stock_quantity: 45,
    is_featured: true,
    has_offer: true,
    variants: { colors: ['Gray', 'Navy Blue', 'Beige', 'Black'], sizes: ['3-seater', '4-seater'] },
    specifications: { material: 'Fabric Upholstery', dimensions: '220x90x85cm', weight_capacity: '500kg' },
  },
  {
    name: 'Garden Patio Dining Set',
    slug: 'garden-patio-dining-set',
    description: 'Beautiful outdoor dining set with weather-resistant table and 6 chairs. Perfect for garden entertaining.',
    category_id: categoryIds['garden-outdoor-living'],
    base_price: 449.99,
    actual_MRP: 699.99,
    discounted_price: 449.99,
    percentage_discount: 36,
    images: ['https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['garden', 'outdoor', 'dining', 'furniture'],
    rating: 4.6,
    review_count: 234,
    stock_quantity: 30,
    is_featured: true,
    is_hot_deal: true,
    variants: null,
    specifications: { pieces: '7 (table + 6 chairs)', material: 'Teak Wood', weather_resistant: 'Yes' },
  },
  {
    name: 'Ergonomic Office Desk Chair',
    slug: 'ergonomic-office-desk-chair',
    description: 'High-back ergonomic office chair with lumbar support and adjustable height. Perfect for long working hours.',
    category_id: categoryIds['office-school-supplies'],
    base_price: 199.99,
    actual_MRP: 319.99,
    discounted_price: 199.99,
    percentage_discount: 37,
    images: ['https://images.pexels.com/photos/1633356/pexels-photo-1633356.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['office', 'chair', 'ergonomic', 'desk'],
    rating: 4.8,
    review_count: 567,
    stock_quantity: 120,
    is_featured: true,
    has_offer: true,
    variants: { colors: ['Black', 'Gray', 'Blue'], sizes: [] },
    specifications: { max_weight: '150kg', material: 'Mesh Back', adjustment: '360° swivel' },
  },
  {
    name: 'Acoustic Guitar Beginner Set',
    slug: 'acoustic-guitar-beginner-set',
    description: 'Complete acoustic guitar set for beginners including guitar, tuner, stand, and capo. Great for learning.',
    category_id: categoryIds['music-instruments'],
    base_price: 129.99,
    actual_MRP: 199.99,
    discounted_price: 129.99,
    percentage_discount: 35,
    images: ['https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['guitar', 'music', 'instrument', 'beginner'],
    rating: 4.5,
    review_count: 445,
    stock_quantity: 80,
    is_new_arrival: true,
    has_offer: true,
    variants: { colors: ['Natural Wood', 'Black', 'Sunburst'], sizes: [] },
    specifications: { type: 'Acoustic', material: 'Spruce Wood', string_type: 'Steel' },
  },
  {
    name: 'Premium Stainless Steel Watch',
    slug: 'premium-stainless-steel-watch',
    description: 'Elegant stainless steel wristwatch with water resistance and sapphire crystal. A timeless classic.',
    category_id: categoryIds['jewelry-watches'],
    base_price: 249.99,
    actual_MRP: 399.99,
    discounted_price: 249.99,
    percentage_discount: 37,
    images: ['https://images.pexels.com/photos/2407175/pexels-photo-2407175.jpeg?auto=compress&cs=tinysrgb&w=800'],
    tags: ['watch', 'jewelry', 'luxury', 'timepiece'],
    rating: 4.9,
    review_count: 678,
    stock_quantity: 150,
    is_featured: true,
    is_hot_deal: true,
    variants: { colors: ['Silver', 'Gold', 'Rose Gold', 'Black'], sizes: [] },
    specifications: { waterproof: '30m', crystal: 'Sapphire', movement: 'Quartz', case: 'Stainless Steel' },
  },
];

export const seedOffers = [
  {
    title: 'Summer Sale - Up to 50% Off',
    description: 'Biggest sale of the season on fashion and electronics',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 50,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/3825517/pexels-photo-3825517.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'Free Shipping Weekend',
    description: 'Free shipping on all orders above $50',
    type: 'banner',
    code: 'FREESHIP',
    discount_type: 'fixed',
    discount_value: 0,
    min_purchase: 50,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
  },
  {
    title: 'Flash Sale: 70% Off Electronics!',
    description: 'Unbeatable deals on the latest gadgets and tech - Don\'t miss out!',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 70,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/3825517/pexels-photo-3825517.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'Fashion Frenzy - 60% Off Everything!',
    description: 'Revamp your wardrobe with designer styles at incredible prices',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 60,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'Home Makeover Sale - Save Big!',
    description: 'Transform your space with up to 50% off home and kitchen essentials',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 50,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/4686822/pexels-photo-4686822.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'Sports Gear Extravaganza!',
    description: 'Gear up for victory with 40% off all sports and outdoor equipment',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 40,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'Book Lovers Paradise - 30% Off!',
    description: 'Dive into new worlds with massive discounts on bestselling books',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 30,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/46274/pexels-photo-46274.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'Beauty Bonanza - Glow Up Now!',
    description: 'Achieve your best look with 50% off premium beauty products',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 50,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/3785147/pexels-photo-3785147.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'Toy Wonderland - Kids Rejoice!',
    description: 'Endless fun awaits with 45% off toys and games for all ages',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 45,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/1134643/pexels-photo-1134643.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'Auto Accessories Blowout!',
    description: 'Upgrade your ride with 35% off automotive parts and accessories',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 35,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'Wellness Revolution - 55% Off!',
    description: 'Invest in your health with unbeatable deals on wellness products',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 55,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'Pet Paradise - Spoil Your Furry Friends!',
    description: 'Show your pets some love with 40% off all pet supplies',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 40,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/4588051/pexels-photo-4588051.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'Mega Clearance - Up to 80% Off!',
    description: 'Final clearance on select items - Prices you won\'t believe!',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 80,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'New Arrivals Alert!',
    description: 'Be the first to shop the latest trends and must-have items',
    type: 'banner',
    discount_type: 'percentage',
    discount_value: 20,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    image_url: 'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    title: 'Hot Deal: Wireless Headphones',
    description: '40% off premium headphones - Limited time!',
    type: 'hot_deal',
    discount_type: 'percentage',
    discount_value: 40,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
  },
  {
    title: 'SAVE20',
    description: '$20 off on orders over $100',
    type: 'coupon',
    code: 'SAVE20',
    discount_type: 'fixed',
    discount_value: 20,
    min_purchase: 100,
    usage_limit: 1000,
    valid_from: new Date().toISOString(),
    valid_until: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
  },
];
